language: generic
sudo: required
services: docker
dist: bionic
install:
- source texlive.sh
cache:
  directories:
  - "/tmp/texlive"
  - "$HOME/.texlive"
script:
- l3build install && l3build ctan -H --show-log-on-error

deploy:
  provider: releases
  api_key:
    secure: M84jq+M4suyCDztoCM8NkYTr+26mzNi1scmaInmKTFFqxPg7fKk6ekDkBzkpfjLcQG3VKf6pHekDAYvO+EmMNvpMznSGkYyrZzc49yDRAuvsMyA1sEN5xXb0F85q+7S+ajeRRXIf+uF1u6xJB1XbBdYMRTn0EYQjIteuj9l8LvT//pW1CcXtGCbHTNO0PeW/y+5IS9syv6GURrdUJnFccuGLVvu1A6Ekg/edTULZtkTPzkqTaicsUa3JOB/BtfuLush3BfdTYeNyIXZ4yFxqvmaueF7uT+P9//LOSJXCmApiHCpqLCjLW1d5L1LFdRb+C/zlsv5jImMVvktWXBFghRkZSBMhvetM6R2gErGzNDA4XA6wZoxaU/6XXAiKjjJUXRokikQAnp26FFXdS84PPCCulueoLQ81UZ0BZM6PiKy+eF5Cj7XTBMUJgKRjX7hBKXDTEC3uLXWaY0Yu336FPc/yExf+hFZkH9fIXgXhqUvsOzaisKR2KC6ZUVPzdbquxm7kIbEV54UzcXaRfPc10wy/l2Wjl5x7R4qIdr+ZaHjpW3fvrQTR2BXlruWR2kLN7PLi9xmHygZtnJmjXfnDjXJ7w91x3nBfqlVcu1eysXLg/aiYx4XgHTQkw0YAxxrSYrbzAiPYpqs/PgWfArGCVBYMMhc9y66obD9PekCngB4=
  file_glob: true
  file: build/distrib/ctan/*.zip
  on:
    repo: u-fischer/chessboard
    tags: true
  prerelease: true
