language: generic
sudo: required
services: docker
dist: bionic
install:
- source texlive.sh
cache:
  directories:
  - "/tmp/texlive"
  - "$HOME/.texlive"
script:
- l3build install && l3build ctan -H --show-log-on-error

deploy:
- provider: releases
  api_key:
    secure: oBkpeu+7YX24ZHoHGiNgtPMdxP0b0WMseWf+QhCUBd3EW7vHk96jv+35vwSypg9dhAyxLD94ndNEodkQIVlq8J19LCQeHi6BM+29jfxLAHp5fzYM30n77NwRZM3qmtvgrgU1ufV1r0OWDX0AIs9O5Yyj/GcYGb4RmUqPOxw6F1Qrf8UKzeDUSDT92ksC1dvmsKP5B4JSeTOxD60QDshonTI1ehW5f2gZdYn+8XBhs5g84wgytW1irKInXXl+J8cMaCp9L+a6vMvX1gME/yX/Kcr+DjhTqWG/elABTjPUP7ChrzfwvTQ+YSWyPiQVyClwsavW0/5tNBUNZe9Rs9dvOov0woORyV9nIF9dY6GAXBZujF9xOsrzXP8WMAOKloONOEmrfettJdVwodk2G47dgIHwxZkRjjkCQHqJ1PZ/rRA7ui0VhaYQOE7XbORcu+fOjli62ju9+m6aFU6jcLKuRPfORbV5BeQVtoMEO8TtpWOjszDS+8xv+Xy7Zz5P4lVFlnlfM3dhGBBQjWBAnc27n0I/e/ISgljquXWa7VUAbTYRHHIKzRdy4DUMsPfA8b4tal1abpgL2SXlYw8KexvrSS5XOoqddkKnBX6hKihSISdNVMQbCZLY1Fqfj7EyMk2UXy/dEzDNCImPTzIZFXwi5UUfOyKAwN2hCbVuHpUmX5c=
  file_glob: true
  file:
  - build/distrib/ctan/*.zip
  skip_cleanup: true
  on:
    tags: true
  prerelease: true
